# AUTO-GENERATED by tools/gen_maps.py from WoWS 15.5.0 `space.settings`.
# Do not edit by hand -- re-run the generator after a client update.
#
# Map recognition for the 8111-for-WoWS server: turn the in-game space name
# into a friendly map name and exact, origin-centred world bounds so the
# overlay can compute precise normalized coordinates (nx/ny) instead of
# auto-fitting. Bounds are world meters: (minX, maxX, minZ, maxZ).
"""World/map recognition table (generated; see tools/gen_maps.py)."""

GAME_VERSION = "15.5.0"

# internal space id (lowercase) -> (friendly_name, minX, maxX, minZ, maxZ)
MAPS = {
    '00_co_ocean': ('Ocean', -800.0, 800.0, -800.0, 800.0),
    '01_solomon_islands': ('Solomon Islands', -700.0, 700.0, -700.0, 700.0),
    '04_archipelago': ('Archipelago', -700.0, 700.0, -700.0, 700.0),
    '05_ring': ('The Ring', -800.0, 800.0, -800.0, 800.0),
    '08_ne_passage': ('Passage', -800.0, 800.0, -800.0, 800.0),
    '10_ne_big_race': ('Big Race', -700.0, 700.0, -700.0, 700.0),
    '13_oc_new_dawn': ('New Dawn', -800.0, 800.0, -800.0, 800.0),
    '14_atlantic': ('Atlantic', -900.0, 900.0, -900.0, 900.0),
    '15_ne_north': ('North', -1000.0, 1000.0, -1000.0, 1000.0),
    '16_oc_bees_to_honey': ('Bees To Honey', -1000.0, 1000.0, -1000.0, 1000.0),
    '17_na_fault_line': ('Fault Line', -900.0, 900.0, -900.0, 900.0),
    '18_ne_ice_islands': ('Ice Islands', -900.0, 900.0, -900.0, 900.0),
    '19_oc_prey': ('Prey', -900.0, 900.0, -900.0, 900.0),
    '20_ne_two_brothers': ('Two Brothers', -900.0, 900.0, -900.0, 900.0),
    '22_tierra_del_fuego': ('Tierra del Fuego', -1000.0, 1000.0, -1000.0, 1000.0),
    '23_shards': ('Shards', -900.0, 900.0, -900.0, 900.0),
    '25_sea_hope': ('Sea Hope', -1000.0, 1000.0, -1000.0, 1000.0),
    '28_naval_mission': ('Naval Mission', -900.0, 900.0, -900.0, 900.0),
    '33_new_tierra': ('New Tierra', -600.0, 600.0, -600.0, 600.0),
    '34_oc_islands': ('Islands', -600.0, 600.0, -600.0, 600.0),
    '35_ne_north_winter': ('North Winter', -1000.0, 1000.0, -1000.0, 1000.0),
    '37_ridge': ('Ridge', -1000.0, 1000.0, -1000.0, 1000.0),
    '38_canada': ('Canada', -1000.0, 1000.0, -1000.0, 1000.0),
    '40_okinawa': ('Okinawa', -900.0, 900.0, -900.0, 900.0),
    '41_conquest': ('Conquest', -900.0, 900.0, -900.0, 900.0),
    '42_neighbors': ('Neighbors', -900.0, 900.0, -900.0, 900.0),
    '44_path_warrior': ('Path Warrior', -1000.0, 1000.0, -1000.0, 1000.0),
    '45_zigzag': ('Zigzag', -1000.0, 1000.0, -1000.0, 1000.0),
    '46_estuary': ('Estuary', -900.0, 900.0, -900.0, 900.0),
    '47_sleeping_giant': ('Sleeping Giant', -900.0, 900.0, -900.0, 900.0),
    '50_gold_harbor': ('Gold Harbor', -900.0, 900.0, -900.0, 900.0),
    '51_greece': ('Greece', -900.0, 900.0, -900.0, 900.0),
    '52_britain': ('Britain', -900.0, 900.0, -900.0, 900.0),
    '53_shoreside': ('Shoreside', -900.0, 900.0, -900.0, 900.0),
    '54_faroe': ('Faroe', -1000.0, 1000.0, -1000.0, 1000.0),
    '55_seychelles': ('Seychelles', -1000.0, 1000.0, -1000.0, 1000.0),
    '56_angelwings': ('AngelWings', -1000.0, 1000.0, -1000.0, 1000.0),
    '58_ridgenew': ('RidgeNew', -1000.0, 1000.0, -1000.0, 1000.0),
    'e14_modernera': ('ModernEra', -2100.0, 2100.0, -2100.0, 2100.0),
    'r01_military_navigation': ('Military Navigation', -900.0, 900.0, -900.0, 900.0),
    's01_navalbase': ('NavalBase', -800.0, 800.0, -800.0, 800.0),
    's02_naval_defense': ('Naval Defense', -900.0, 900.0, -900.0, 900.0),
    's03_labyrinth': ('Labyrinth', -900.0, 900.0, -900.0, 900.0),
    's06_atoll': ('Atoll', -1000.0, 1000.0, -1000.0, 1000.0),
    's07_advance': ('Advance', -700.0, 700.0, -700.0, 700.0),
    's09_lepve': ('LePVE', -900.0, 900.0, -900.0, 900.0),
    's10_uss_cl': ('USS CL', -1000.0, 1000.0, -1000.0, 1000.0),
    's12_ww2_op1': ('WW2 OP1', -1000.0, 1000.0, -1000.0, 1000.0),
    's13_ww2_op2': ('WW2 OP2', -900.0, 900.0, -900.0, 900.0),
    's14_ww2_op3': ('WW2 OP3', -900.0, 900.0, -900.0, 900.0),
}


def normalize_space_id(raw):
    """Normalize a raw space identifier to a MAPS lookup key.

    Accepts values like ``spaces/13_OC_new_dawn``, ``13_OC_new_dawn`` or a bare
    geometry path; returns the lowercased trailing component (or None).
    """
    if not raw:
        return None
    s = str(raw).replace("\\", "/").strip().strip("/")
    if not s:
        return None
    if "/" in s:
        s = s.rsplit("/", 1)[-1]
    return s.lower() or None


def resolve_map(raw):
    """Resolve a raw space name to {id, name, bounds} or None if unknown."""
    key = normalize_space_id(raw)
    if not key:
        return None
    info = MAPS.get(key)
    if info is None:
        return None
    name, min_x, max_x, min_z, max_z = info
    return {"id": key, "name": name, "bounds": [min_x, max_x, min_z, max_z]}


def friendly_name(raw):
    """Friendly display name for a raw space id, or None if unknown."""
    hit = resolve_map(raw)
    return hit["name"] if hit else None
