#!/usr/bin/env python3
# MIT License
# Copyright (c) 2026 Tz-WIND/Lex_q
#
# SPDX-License-Identifier: MIT
"""Generate server/maps.py from unpacked WoWS `space.settings` files.

This is the *reproducible* source of the map-recognition table used by the
server to turn the in-game space name (e.g. ``spaces/13_OC_new_dawn``) into a
friendly map name and exact, origin-centred world bounds for precise minimap
normalization (nx/ny).

How the bounds are derived (verified against WoWS 15.5 client data):
  * `space.settings` stores `<bounds>` as an integer *chunk* grid, either as
    attributes (`<bounds minX=".." .. />`) or child elements (`<minX>..`).
  * Every battle map satisfies ``minX + maxX == -1`` -> the playable square is
    centred on the world origin (0, 0).
  * Real-world size of one chunk = `<chunkSize>` meters (default 100; a few
    special spaces use 300). World half-extent = halfChunks * chunkSize, so:
        minX_world = minX_chunk * chunkSize
        maxX_world = (maxX_chunk + 1) * chunkSize     (symmetric about 0)
  * WoWS world X maps to minimap X (east); world Z (space.settings "Y") maps to
    minimap Y (north). The server uses (minX, maxX, minZ, maxZ).

Usage:
    # 1) unpack space.settings from your installed client (any version):
    #    wowsunpack.exe "<game>/bin/<build>/idx" -p "<game>/res_packages" \
    #        -I "*space.settings" -x -o "<SPACES_PARENT>"
    # 2) point SPACES_DIR at the produced `spaces/` folder and run:
    uv run python tools/gen_maps.py
"""

import glob
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
# folder that contains the unpacked `spaces/<map>/space.settings` tree
SPACES_DIR = os.path.join(REPO, "\u53c2\u8003mods", "SDK", "_extracted_15.5", "spaces")
OUT = os.path.join(REPO, "server", "maps.py")
GAME_VERSION = "15.5.0"
DEFAULT_CHUNK = 100.0

# Region/grid codes that sit between the numeric prefix and the real name.
_REGION = {"co", "ne", "na", "oc", "se", "sa", "ec", "we"}
# Exclude non-battle spaces (port scenes, shipyards, exteriors).
_SKIP_PREFIX = ("dock", "exterior", "shipyard")

# Curated display names where the cleaned id differs from the in-game name.
_FRIENDLY = {
    "00_co_ocean": "Ocean",
    "05_ring": "The Ring",
    "22_tierra_del_fuego": "Tierra del Fuego",
}


def _num(text, name):
    m = re.search(r"<%s>\s*(-?\d+(?:\.\d+)?)\s*</%s>" % (name, name), text)
    if m:
        return float(m.group(1))
    m = re.search(name + r'\s*=\s*"(-?\d+(?:\.\d+)?)"', text)
    return float(m.group(1)) if m else None


def _derive_name(folder):
    parts = folder.split("_")
    if parts and re.match(r"^[a-z]?\d+$", parts[0], re.I):
        parts = parts[1:]
    if parts and parts[0].lower() in _REGION:
        parts = parts[1:]
    # preserve internal capitalization (e.g. ModernEra), just upper the first char
    words = [p[:1].upper() + p[1:] for p in parts if p]
    return " ".join(words) or folder


def collect():
    rows = {}
    for p in sorted(glob.glob(os.path.join(SPACES_DIR, "*", "space.settings"))):
        folder = os.path.basename(os.path.dirname(p))
        if folder.lower().startswith(_SKIP_PREFIX):
            continue
        text = open(p, "rb").read().decode("utf-8", "ignore")
        bx = [_num(text, k) for k in ("minX", "maxX", "minY", "maxY")]
        if None in bx:
            continue
        min_x, max_x, min_y, max_y = (int(v) for v in bx)
        chunk = _num(text, "chunkSize") or DEFAULT_CHUNK
        key = folder.lower()
        name = _FRIENDLY.get(key, _derive_name(folder))
        rows[key] = (
            name,
            min_x * chunk,
            (max_x + 1) * chunk,
            min_y * chunk,
            (max_y + 1) * chunk,
        )
    return rows


_TEMPLATE = '''# AUTO-GENERATED by tools/gen_maps.py from WoWS __VERSION__ `space.settings`.
# Do not edit by hand -- re-run the generator after a client update.
#
# Map recognition for the 8111-for-WoWS server: turn the in-game space name
# into a friendly map name and exact, origin-centred world bounds so the
# overlay can compute precise normalized coordinates (nx/ny) instead of
# auto-fitting. Bounds are world meters: (minX, maxX, minZ, maxZ).
"""World/map recognition table (generated; see tools/gen_maps.py)."""

GAME_VERSION = "__VERSION__"

# internal space id (lowercase) -> (friendly_name, minX, maxX, minZ, maxZ)
MAPS = {
__ROWS__}


def normalize_space_id(raw):
    """Normalize a raw space identifier to a MAPS lookup key.

    Accepts values like ``spaces/13_OC_new_dawn``, ``13_OC_new_dawn`` or a bare
    geometry path; returns the lowercased trailing component (or None).
    """
    if not raw:
        return None
    s = str(raw).replace("\\\\", "/").strip().strip("/")
    if not s:
        return None
    if "/" in s:
        s = s.rsplit("/", 1)[-1]
    return s.lower() or None


def resolve_map(raw):
    """Resolve a raw space name to {id, name, bounds} or None if unknown."""
    key = normalize_space_id(raw)
    if not key:
        return None
    info = MAPS.get(key)
    if info is None:
        return None
    name, min_x, max_x, min_z, max_z = info
    return {"id": key, "name": name, "bounds": [min_x, max_x, min_z, max_z]}


def friendly_name(raw):
    """Friendly display name for a raw space id, or None if unknown."""
    hit = resolve_map(raw)
    return hit["name"] if hit else None
'''


def main():
    rows = collect()
    body = "".join(
        '    %r: (%r, %.1f, %.1f, %.1f, %.1f),\n' % (k, v[0], v[1], v[2], v[3], v[4])
        for k, v in sorted(rows.items())
    )
    content = _TEMPLATE.replace("__VERSION__", GAME_VERSION).replace("__ROWS__", body)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print("wrote %s (%d maps)" % (OUT, len(rows)))


if __name__ == "__main__":
    main()
